# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "asphalt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Cracked Asphalt"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Cracked Asphalt Studio"
description              : "Simple and functional outdoor gear. Make it yourself guides and tutorials."
url                      : "https://www.crackedasphalt.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" #"/minimal-mistakes" # the subpath of your site, e.g. "/blog"
repository               : "crackedasphalt/crackedasphalt.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/500x300.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/cracked-asphalt-studio-mtn-txt-col-900x145.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : " " # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : true # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "cracked_asphalt"
facebook:
  username               : &facebook "crackedasphalt"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/cracked-asphalt-studio-cir-blk-1000x1000.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Organization" # Person or Organization (defaults to Person)
  name                   : "Cracked Asphalt Studio" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
#    - "https://twitter.com/cracked_asphalt"
#    - "https://www.facebook.com/crackedasphalt"
    - "https://instagram.com/crackedasphaltstudio"
    - "https://www.reddit.com/user/crackedasphalt"

# Analytics
analytics:
  provider               : "google-tag-manager" # false (default), "google", "google-universal", "google-gtag", "google-tag-manager", "custom"
  google:
    tracking_id          : "GTM-NQD3RKPW"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Cracked Asphalt"
  avatar           : "/assets/images/cracked-asphalt-studio-mtn-col-200x200.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  avatar_format    : # "circle" (default) or "square"
  bio              : ""
  location         : "San Francisco, CA"
  email            : "hello@crackedasphalt.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      #url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/cracked_asphalt"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      #url: "https://facebook.com/crackedasphalt"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      #url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      #url: "https://www.linkedin.com/in/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/crackedasphaltstudio"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit-square"
      url: "https://www.reddit.com/user/crackedasphalt"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      #url: "https://www.youtube.com/@crackedasphalt"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/cracked_asphalt"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      #url: "https://www.facebook.com/crackedasphalt"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/crackedasphaltstudio"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/u/crackedasphalt"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      #url: "https://www.reddit.com/u/crackedasphalt"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
page_excerpts: true # Jekyll 4.1.1 or higher required

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # Include documents in _pages in search
  - scope:
      path: "_pages"
    values:
      search: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      show_date: true
      excerpt:
      header:
        show_overlay_excerpt: false
        overlay_color: "#546375" #"#5e616c"
        overlay_filter: 0.2
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      header:
        show_overlay_excerpt: true
        overlay_color: "#546375" #"#5e616c"
        overlay_filter: .5
        overlay_image: /assets/images/home/home-page-overlay.jpg
        og_image: /assets/images/home/home-page-overlay-og.jpg
      sitemap: true
      author_profile: false # false, true - Displays author profile on page left
      author: # Author name - Overrides the default site author.
  # patterns
  - scope:
      path: ""
      type: patterns
    values:
      layout: pattern
      classes: 
      share: true
      search: true

# Form settings for Email signup form

## Convertkit
signup-form:
  show_form: true 
  description: Subscribe to be first to learn about new guides, patterns, and upcoming releases.
  thanks_message: Please check your email to confirm your subscription to our updates.
  confirmed_message: 

collections:
#  collection-example-1: # Change this value to match the name of collection
#    output: true
#    permalink: /:collection/:path/
#  collection-example-2: # Change this value to match the name of collection
#    output: true
#    permalink: /:collection/:path/
  patterns:
    output: true
    permalink: /:collection/:path/